### PR TITLE
Fix Glulx transcript bug

### PR DESCRIPTION
**Pull request by Keltena**
Added code to ensure completed input is sent to echo stream. This fixes the bug that caused transcripts of Glulx games to omit the player's commands.

### CODE REVIEW

**Comment by Keltena** [comment]
Ping @davidar

**Comment by davidar** [comment]
I assume you're talking about https://github.com/tccowper/fabularium/issues/9

I haven't maintained this repo in quite a while, but thanks for the fix

**Comment by Keltena** [comment]
Thanks! Any chance you could tag a release to update F-Droid with those changes?

**Comment by Keltena** [comment]
> Thanks! Any chance you could tag a release to update F-Droid with those changes?

Belated second ping @davidar

(If you'd rather not be bugged further about this at all, then understood; I only just realized you might not have seen this in this first place.)

**Comment by davidar** [comment]
Done: https://github.com/davidar/fabularium/releases/tag/v1.5.1

I think fdroid should automatically pick up the new tag soon?

Honestly I haven't used this app in a while, so let me know if you're interested in taking over maintenance, happy to give you extra permissions on the repo.

**Comment by Keltena** [comment]
> Done: https://github.com/davidar/fabularium/releases/tag/v1.5.1
> 
> I think fdroid should automatically pick up the new tag soon?

Thanks! I'll keep an eye out for it.

> Honestly I haven't used this app in a while, so let me know if you're interested in taking over maintenance, happy to give you extra permissions on the repo.

Sure, I'd be happy to.

**Comment by davidar** [comment]
Cool, I added you as a collaborator, you should get an email about it

**Pull request merged**
